---
apiVersion: v1
kind: Service
metadata:
  name: funder-bridge
  namespace: default
  labels:
    app: funder-bridge
    environment: production
spec:
  selector:
    app: funder-bridge
    environment: production
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
